"use client"

import React from 'react';
import { PlusCircle, Edit3, BarChart3, Package, Sparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';

const AdminDashboard = () => {
  const router = useRouter();

  const handleCardClick = (path: string) => {
    router.push(path);
  };

  const cards = [
    {
      id: 'form-builder',
      title: 'Form Builder',
      description: 'Create new dynamic forms with a versatile logic engine',
      icon: PlusCircle,
      path: '/admin/form-builder',
      gradient: 'from-indigo-500 to-purple-500',
    },
    {
      id: 'edit-form',
      title: 'Edit Forms',
      description: 'Configure and update your existing form architectures',
      icon: Edit3,
      path: '/admin/edit-forms',
      gradient: 'from-purple-500 to-pink-500',
    },
    {
      id: 'Summary',
      title: 'AI Summary',
      description: 'View visual insights generated by the AI sentiment engine',
      icon: Package,
      path: '/admin/summary',
      gradient: 'from-pink-500 to-rose-500',
    },
    {
      id: 'dashboard',
      title: 'Live Dashboard',
      description: 'Monitor real-time analytics and form responses',
      icon: BarChart3,
      path: '/admin/dashboard',
      gradient: 'from-blue-500 to-cyan-500',
    }
  ];

  return (
    <div className="min-h-full bg-transparent text-white relative">
      <main className="relative z-10 max-w-7xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
        {/* Welcome Section */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="mb-16 text-center sm:text-left"
        >
          <h2 className="text-4xl sm:text-6xl font-extrabold text-white mb-4 tracking-tight">
            Welcome back, <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-pink-400">Admin</span>
          </h2>
          <p className="text-zinc-400 text-lg sm:text-xl font-light max-w-2xl">
           Choose a section below to create forms, view responses, or see AI insights.
          </p>
        </motion.div>

        {/* Cards Grid */}
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.2, ease: "easeOut" }}
          className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6"
        >
          {cards.map((card, idx) => {
            const IconComponent = card.icon;
            return (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1 * idx }}
                key={card.id}
                onClick={() => handleCardClick(card.path)}
                className="group relative bg-zinc-900/40 border border-zinc-800/60 rounded-3xl p-8 cursor-pointer transform transition-all duration-500 hover:bg-zinc-800/60 backdrop-blur-xl overflow-hidden"
              >
                {/* Subtle Hover Gradient Inside Card */}
                <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

                {/* Card Content */}
                <div className="relative z-10 flex flex-col h-full">
                  {/* Icon */}
                  <div className={`w-14 h-14 bg-gradient-to-br ${card.gradient} rounded-2xl flex items-center justify-center mb-6 shadow-inner group-hover:scale-110 transition-transform duration-500`}>
                    <IconComponent className="w-7 h-7 text-white" />
                  </div>

                  {/* Title */}
                  <h3 className="text-xl font-bold text-zinc-100 mb-2 tracking-tight">
                    {card.title}
                  </h3>

                  {/* Description */}
                  <p className="text-zinc-400 text-sm leading-relaxed font-medium mb-8 flex-grow">
                    {card.description}
                  </p>

                  {/* Arrow Indicator */}
                  <div className="flex items-center text-indigo-400 font-semibold group-hover:text-pink-400 transition-colors duration-300 mt-auto">
                    <span className="text-sm">Launch Module</span>
                    <svg
                      className="w-4 h-4 ml-2 transform group-hover:translate-x-2 transition-transform duration-300"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
                    </svg>
                  </div>
                </div>

                {/* Outer Subtle Border Glow on Hover */}
                <div className={`absolute inset-0 bg-gradient-to-r ${card.gradient} opacity-0 group-hover:opacity-[0.05] transition-opacity duration-500 pointer-events-none rounded-3xl`} />
              </motion.div>
            );
          })}
        </motion.div>
      </main>
    </div>
  );
};

export default AdminDashboard;
